---
app:
  iOS:
    - id: 443904275
      name: "iOSアプリ名前"
      countryCode: 
        - jp
  android:
    - id: jp.naver.line.android
      name: "Androidアプリ名前"
      languageCode:
        - ja
        - en

cron:
  time: '*/1 * * * *'
  timeZone: Asia/Tokyo

firstTimeIgnore: false
outputs: 2
maxConnections: 1

slack:
  use: true
  webhook: https://xxxxxxxxxxxxxxxxxxx
  channel: channelname

email:
  use: false
  smtp:
    host: smtp.gmail.com
    port: 465
    ssl: true
    auth:
      user: 'username@gmail.com'
      pass: 'userpassword'
  from: 'sendFrom@mail.com'
  to: 'sendTo@mail.com'
